credentials:
  usernames:
    lucas1:
      email: lucas1@gmail.com
      logged_in: False
      name: Lucas Primeiro
      password: 123ert
    lucas2:
      email: lucas2@gmail.com
      logged_in: False
      name: Lucas Segundo
      password: 456abc
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name